// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "2318537c-a18c-4672-812c-fe73b9b62d78");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1704481055);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1704483044);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{f592b85c-01e3-4ce2-851c-574f4d79c6cc}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1704481052);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 142);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1a0b19a5-d62d-4cca-a399-195c0db0bfe3}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1704481054);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1704481568965");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1704503168965");
user_pref("browser.search.region", "HU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20231211174248");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.defaultBrowserCheckCount", 1);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20231211174248");
user_pref("browser.startup.homepage_override.mstone", "121.0");
user_pref("browser.startup.lastColdStartupCheck", 1704483044);
user_pref("browser.topsites.contile.lastFetch", 1704483044);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1704481054059");
user_pref("distribution.iniFile.exists.appversion", "121.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "HU");
user_pref("dom.push.userAgentID", "711382b772bb4ba49a51de5327cb11f9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231211174248");
user_pref("extensions.lastAppVersion", "121.0");
user_pref("extensions.lastPlatformVersion", "121.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"977307d5-69b1-43f9-885b-2bdba16302cf\",\"pictureinpicture@mozilla.org\":\"87f4a054-0c4f-421c-b5c9-e0d14310de92\",\"screenshots@mozilla.org\":\"d2e8b22f-5d8a-471c-bdb5-83b3a69e1164\",\"webcompat-reporter@mozilla.org\":\"b8200ad9-18f7-4d9d-959e-6193140d838c\",\"webcompat@mozilla.org\":\"6e109837-4400-445b-8e12-a63dc351b2cb\",\"default-theme@mozilla.org\":\"26fdc952-f9a2-405d-bbc6-c408f3fceaa3\",\"addons-search-detection@mozilla.com\":\"e672e1ee-dd33-4cc5-a9a9-7ae7b9a294e2\",\"google@search.mozilla.org\":\"e70b7ee4-e3c8-4b0a-bc9b-31c4a9108e1e\",\"amazondotcom@search.mozilla.org\":\"21151100-763b-4425-bf57-3c25ee5ba657\",\"wikipedia@search.mozilla.org\":\"213b8ff8-f4fd-46e1-9382-ea6ae4cdb76d\",\"bing@search.mozilla.org\":\"eb7cf0ce-5eb0-4bee-9ba9-ee94d1cee602\",\"ddg@search.mozilla.org\":\"d46f6356-dcbf-40ba-9dff-8e163249375b\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("identity.fxaccounts.toolbar.defaultVisible", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.fxaButtonVisibility", "{\"slug\":\"mozillaaccounts-toolbar-button-default-visibility-existing-user\",\"branch\":{\"slug\":\"treatment-a\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"fxaButtonVisibility\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"MozillaAccounts toolbar button default visibility rollout\",\"userFacingDescription\":\"This experiment measures the impact of showing the Firefox Accounts toolbar button by default for signed-out users.\",\"lastSeen\":\"2024-01-05T18:57:34.074Z\",\"featureIds\":[\"fxaButtonVisibility\"],\"prefs\":[{\"name\":\"identity.fxaccounts.toolbar.defaultVisible\",\"branch\":\"user\",\"featureId\":\"fxaButtonVisibility\",\"variable\":\"boolean\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.fxaButtonVisibility.boolean", true);
user_pref("nimbus.syncdefaultsstore.pocketNewtab", "{\"slug\":\"rollout-of-share-of-voice-for-sponsored-topsites-rest-of-world\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"pocketNewtab\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Rollout of Share-of-Voice for Sponsored TopSites Rest of World\",\"userFacingDescription\":\"Rollout of the Share-of-Voice feature to dynamically manage ad inventory on the NewTab page.\",\"lastSeen\":\"2024-01-05T18:57:34.234Z\",\"featureIds\":[\"pocketNewtab\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.topSitesContileSovEnabled", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2024-01-05T18:57:34.248Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "e8b574fc-fba1-47e7-94a5-e3ee663090ce");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1704483042);
user_pref("toolkit.telemetry.cachedClientID", "5362d285-b7cd-404c-b795-1ab68b4cbc61");
user_pref("toolkit.telemetry.previousBuildID", "20231211174248");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
